### ISSUE TITLE
Only first instance converted to sheet music when exporting to PDF

### ISSUE THREAD

**Issue by iforwms** [TilBlechschmidt/obsidian-plugin-abcjs#9]
Using the two examples from the readme, both are rendered correctly in Obsidian preview mode, but only the first instance is rendered when exporting to PDF. See the screenshots below.

### Obsidian Edit Mode
![image](https://user-images.githubusercontent.com/10304616/118581465-49872a00-b7c4-11eb-8a93-79ab2085332e.png)

### Obsidian Preview Mode
![image](https://user-images.githubusercontent.com/10304616/118581493-54da5580-b7c4-11eb-835f-b43570fa0b66.png)

### Exported PDF
![image](https://user-images.githubusercontent.com/10304616/118581586-750a1480-b7c4-11eb-8dd6-7a82c7a19aed.png)

**Comment by TilBlechschmidt** [comment]
Thank you for the bug report! Unfortunately, I do not have the capacity to investigate at the moment. However, Pull Requests are very welcome if anybody wants to take on the issue 🙂

**Comment by TilBlechschmidt** [comment]
Hi there @stephengrice.

Thank you ever so much for submitting the pull request, I highly appreciate it! I've created the plugin what feels like ages ago and it has been gaining popularity ever since — even though I do not even use Obsidian actively (which is why other issues have been stuck for a while). So seeing someone take on one of the challenges and submitting a fix is lovely to see 😊

Your PR looks good! I'll merge it and create a new release in a bit.

**Comment by TilBlechschmidt** [comment]
New release has been published. Version 1.0.4 should be live now!

**Comment by stephengrice** [comment]
Awesome! Thanks for getting back to me so quickly on this!
